package intent

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/dshakes/halos/internal/policy"
	"github.com/dshakes/halos/internal/yamledit"
)

// Enable is `halo enable mcp|hook`: exactly one of MCP or Hook is set.
type Enable struct {
	MCP  *policy.MCPServer
	Hook *policy.Hook
	// Name of the toggle (defaults to the MCP server name; required for hooks).
	Name string
	// For is who gets it: "all" (a profile change), a ring name, "N%",
	// "group:<g>" or "user:<id>" (a client-axis Toggle).
	For     string
	Owner   string
	Expires string // YYYY-MM-DD; default 90 days from Now
	Now     time.Time
}

// rule parses For into a toggle rule.
func (r *Repo) rule(target string) (policy.ToggleRule, error) {
	switch {
	case strings.HasSuffix(target, "%"):
		pct, err := strconv.ParseFloat(strings.TrimSuffix(target, "%"), 64)
		if err != nil || pct <= 0 || pct > 100 {
			return policy.ToggleRule{}, fmt.Errorf("intent: --for %q: want a percent in (0,100]", target)
		}
		return policy.ToggleRule{Name: "percent", Percent: &pct}, nil
	case strings.HasPrefix(target, "group:"):
		return policy.ToggleRule{Name: "group", Groups: []string{strings.TrimPrefix(target, "group:")}}, nil
	case strings.HasPrefix(target, "user:"):
		return policy.ToggleRule{Name: "user", Users: []string{strings.TrimPrefix(target, "user:")}}, nil
	}
	ring := strings.TrimPrefix(target, "ring:")
	for _, n := range ringNames(r.Org) {
		if n == ring {
			return policy.ToggleRule{Name: ring, Rings: []string{ring}}, nil
		}
	}
	return policy.ToggleRule{}, fmt.Errorf("intent: --for %q: want all, a ring %v, N%%, group:<name> or user:<id>", target, ringNames(r.Org))
}

// Enable adds an MCP server or hook. For "all" it appends to the GA ring's
// profile (a stub profile document in simple mode); otherwise it writes a
// client-axis Toggle for the targeted cohort, killable with `halo kill`.
func (r *Repo) Enable(e Enable) (*Change, error) {
	if (e.MCP == nil) == (e.Hook == nil) {
		return nil, fmt.Errorf("intent: enable needs exactly one of an MCP server or a hook")
	}
	what := "hook"
	if e.MCP != nil {
		what = "mcp server " + e.MCP.Name
		if e.Name == "" {
			e.Name = e.MCP.Name
		}
	}
	ga, err := r.GA()
	if err != nil {
		return nil, err
	}
	prof, err := r.Org.ResolveProfile(ga.Profile)
	if err != nil {
		return nil, err
	}
	if e.For == "" || e.For == "all" {
		return r.enableAll(ga.Profile, prof, e)
	}
	if err := validName("toggle", e.Name); err != nil {
		return nil, err
	}
	for _, t := range r.Org.Toggles {
		if t.Name == e.Name {
			return nil, fmt.Errorf("intent: toggle %q already exists", e.Name)
		}
	}
	rule, err := r.rule(e.For)
	if err != nil {
		return nil, err
	}
	if e.Expires == "" {
		e.Expires = e.Now.AddDate(0, 0, 90).Format(policy.ToggleDateLayout)
	}
	if e.Owner == "" {
		e.Owner = "platform"
		if g := r.Org.Identity.AdminGroups; len(g) > 0 {
			e.Owner = g[0]
		}
	}
	patch := policy.TogglePatch{}
	if e.MCP != nil {
		patch.MCPServers = []policy.MCPServer{*e.MCP}
	} else {
		patch.Hooks = []policy.Hook{*e.Hook}
	}
	t := &policy.Toggle{Meta: meta(policy.KindToggle, e.Name), Description: fmt.Sprintf("Enable %s for %s", what, e.For),
		Owner: e.Owner, Expires: e.Expires, Axis: policy.AxisClient, Rules: []policy.ToggleRule{rule},
		Client: &policy.ToggleClient{Harnesses: map[string]policy.TogglePatch{}}}
	for _, h := range sortedKeys(prof.Harnesses) {
		t.Client.Harnesses[h] = patch
	}
	b, err := docYAML(policy.KindToggle, fmt.Sprintf("Generated by `halo enable`. Kill it fleet-wide, no release needed:\n  halo kill %s --reason \"...\"", e.Name), t)
	if err != nil {
		return nil, err
	}
	c := newChange(r.Dir)
	c.Files["toggles/"+e.Name+".yaml"] = b
	c.Notes = append(c.Notes, fmt.Sprintf("widen it later with --for all, or remove toggles/%s.yaml by %s", e.Name, e.Expires))
	return c, nil
}

func (r *Repo) enableAll(name string, resolved *policy.Profile, e Enable) (*Change, error) {
	c := newChange(r.Dir)
	path, item := []string{"hooks", "items"}, any(e.Hook)
	if e.MCP != nil {
		path, item = []string{"mcp", "servers"}, e.MCP
		for _, s := range resolved.MCP.Servers {
			if s.Name == e.MCP.Name {
				return nil, fmt.Errorf("intent: profile %q already has mcp server %q", name, s.Name)
			}
		}
	}
	d, err := yamledit.Find(r.Dir, policy.KindProfile, name)
	if err != nil {
		if !r.Simple() {
			return nil, fmt.Errorf("intent: %w", err)
		}
		// Simple mode: the profile is generated; a stub overlays it.
		stub := struct {
			policy.Meta `yaml:",inline"`
			MCP         *policy.MCP   `yaml:"mcp,omitempty"`
			Hooks       *policy.Hooks `yaml:"hooks,omitempty"`
		}{Meta: meta(policy.KindProfile, name)}
		if e.MCP != nil {
			stub.MCP = &policy.MCP{Servers: []policy.MCPServer{*e.MCP}}
		} else {
			stub.Hooks = &policy.Hooks{Hooks: []policy.Hook{*e.Hook}}
		}
		b, err := docYAML(policy.KindProfile, fmt.Sprintf("Overlays profile %s from halos.yaml (explicit fields win; deny lists and hooks add up).\n`halo explain` shows the merged profile.", name), stub)
		if err != nil {
			return nil, err
		}
		c.Files["profiles/"+name+".yaml"] = b
		return c, nil
	}
	data := d.Data
	// A child's servers list replaces its parent's: carry the inherited ones over.
	if e.MCP != nil && d.Get("mcp", "servers") == nil {
		for _, s := range resolved.MCP.Servers {
			if data, err = appendSeq(d, data, name, path, s); err != nil {
				return nil, err
			}
		}
	}
	if data, err = appendSeq(d, data, name, path, item); err != nil {
		return nil, err
	}
	c.Files[d.Rel] = data
	return c, nil
}

// appendSeq appends item to path in data (d's file after earlier edits).
func appendSeq(d *yamledit.Doc, data []byte, name string, path []string, item any) ([]byte, error) {
	m, err := yamledit.Parse(data, policy.KindProfile, name)
	if err != nil || m == nil {
		return nil, fmt.Errorf("intent: reparse %s: %v", d.Rel, err)
	}
	nd := &yamledit.Doc{Path: d.Path, Rel: d.Rel, Data: data, Mapping: m}
	out, err := nd.AppendSeq(path, item)
	if err != nil {
		return nil, fmt.Errorf("intent: %w", err)
	}
	return out, nil
}
