//go:build uat

// Package konguat is the real-Kong UAT: halo-kong as a Go plugin server inside a digest-pinned
// Kong OSS (db-less), driven over HTTPS like a CLI would, with two mock upstreams recording what
// reached them and a halo-server issuing the signed kill list. scripts/uat-kong.sh builds and
// starts the stack and exports the UAT_* variables; this file asserts and writes
// test/uat/KONG-REPORT.md.
package konguat

import (
	"bytes"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/dshakes/halos/internal/gateway"
	"github.com/dshakes/halos/internal/identity/identitytest"
	"github.com/dshakes/halos/internal/policy"
)

const (
	aud     = "halos-gateway"
	issuer  = "http://mock-a:8080" // what Kong's plugin sees; the test reaches the same mock on a published port
	killTTL = 45 * time.Second     // halo-kong polls the kill list every 10s; allow several polls
)

func getenv(k, def string) string {
	if v := os.Getenv(k); v != "" {
		return v
	}
	return def
}

var (
	kongURL   = "https://127.0.0.1:" + getenv("UAT_KONG_PORT", "18443")
	statusURL = "http://127.0.0.1:" + getenv("UAT_STATUS_PORT", "18100")
	mockAURL  = "http://127.0.0.1:" + getenv("UAT_MOCK_A_PORT", "18081")
	mockBURL  = "http://127.0.0.1:" + getenv("UAT_MOCK_B_PORT", "18082")
	serverURL = "http://127.0.0.1:" + getenv("UAT_SERVER_PORT", "18090")
)

// ---- report ----

type row struct {
	group, name, evidence string
	pass                  bool
}

var (
	rowsMu sync.Mutex
	rows   []row
)

// check records one scenario outcome (and fails the test without stopping it, so the
// report always covers every scenario).
func check(t *testing.T, group, name string, ok bool, format string, a ...any) {
	t.Helper()
	ev := strings.ReplaceAll(fmt.Sprintf(format, a...), "|", `\|`)
	rowsMu.Lock()
	rows = append(rows, row{group, name, ev, ok})
	rowsMu.Unlock()
	if !ok {
		t.Errorf("FAIL %s: %s: %s", group, name, ev)
	}
}

func TestMain(m *testing.M) {
	code := m.Run()
	writeReport(code == 0)
	os.Exit(code)
}

func writeReport(allPass bool) {
	var b strings.Builder
	verdict := "PASS"
	if !allPass {
		verdict = "FAIL"
	}
	fmt.Fprintf(&b, "# halo-kong in real Kong OSS: UAT report\n\n")
	fmt.Fprintf(&b, "Generated by `make uat-kong` (`scripts/uat-kong.sh`, `test/uat/kong`) on %s. Overall: **%s**.\n\n", time.Now().UTC().Format(time.RFC3339), verdict)
	fmt.Fprintf(&b, "| | |\n|---|---|\n| Kong | `%s` (OSS, db-less, declarative config) |\n| Image | `%s` |\n", getenv("UAT_KONG_VERSION", "unknown"), getenv("UAT_KONG_IMAGE", "unknown"))
	fmt.Fprintf(&b, "| Plugin | `halo-kong` as a Go plugin server (go-pdk), built from this tree |\n| Config | `halo gateway deck` from `examples/acme-corp` + `test/uat/kong/policy` |\n| Upstreams | two mock model servers (`test/uat/mock`) |\n\n")
	fmt.Fprintf(&b, "Kong Enterprise is **UNVERIFIED**: only the OSS image was run.\n\n")
	group := ""
	for _, r := range rows {
		if r.group != group {
			group = r.group
			fmt.Fprintf(&b, "\n## %s\n\n| Scenario | Result | Evidence |\n|---|---|---|\n", group)
		}
		res := "PASS"
		if !r.pass {
			res = "**FAIL**"
		}
		fmt.Fprintf(&b, "| %s | %s | %s |\n", r.name, res, r.evidence)
	}
	if err := os.WriteFile("../KONG-REPORT.md", []byte(b.String()), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write report:", err)
	}
}

// ---- plumbing ----

var kongClient = &http.Client{
	Timeout:       60 * time.Second,
	Transport:     &http.Transport{TLSClientConfig: &tls.Config{InsecureSkipVerify: true}}, //nolint:gosec // Kong's generated self-signed cert
	CheckRedirect: func(*http.Request, []*http.Request) error { return http.ErrUseLastResponse },
}

type reply struct {
	code int
	hdr  http.Header
	body string
}

func (r reply) String() string { return fmt.Sprintf("%d %s", r.code, trunc(r.body, 160)) }

func trunc(s string, n int) string {
	s = strings.ReplaceAll(s, "\n", " ")
	if len(s) > n {
		return s[:n] + "..."
	}
	return s
}

// call POSTs body to Kong. host, when set, overrides the Host header (Kong routes by it).
func call(t *testing.T, path, token, body string, hdr map[string]string) reply {
	t.Helper()
	return callHost(t, "", path, token, body, hdr)
}

func callHost(t *testing.T, host, path, token, body string, hdr map[string]string) reply {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, kongURL+path, strings.NewReader(body))
	if err != nil {
		t.Fatal(err)
	}
	req.Header.Set("Content-Type", "application/json")
	if token != "" {
		req.Header.Set("Authorization", "Bearer "+token)
	}
	for k, v := range hdr {
		req.Header.Set(k, v)
	}
	if host != "" {
		req.Host = host
	}
	resp, err := kongClient.Do(req)
	if err != nil {
		t.Fatalf("POST %s: %v", path, err)
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	return reply{resp.StatusCode, resp.Header, string(b)}
}

func msg(model string) string {
	return fmt.Sprintf(`{"model":%q,"max_tokens":8,"messages":[{"role":"user","content":"hi"}]}`, model)
}

func mint(t *testing.T, email string, groups ...string) string {
	t.Helper()
	return mintAud(t, aud, email, groups...)
}

func mintAud(t *testing.T, audience, email string, groups ...string) string {
	t.Helper()
	q := url.Values{"email": {email}, "aud": {audience}}
	if len(groups) > 0 {
		q.Set("groups", strings.Join(groups, ","))
	}
	resp, err := http.Get(mockAURL + "/_uat/mint?" + q.Encode())
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		t.Fatalf("mint: %d %s", resp.StatusCode, b)
	}
	return string(b)
}

// rec is one request a mock upstream saw.
type rec struct {
	Path    string              `json:"path"`
	Query   string              `json:"query"`
	Headers map[string][]string `json:"headers"`
	Body    string              `json:"body"`
}

func (r rec) h(k string) string {
	for hk, v := range r.Headers {
		if strings.EqualFold(hk, k) && len(v) > 0 {
			return v[0]
		}
	}
	return ""
}

func (r rec) model() string {
	var b struct {
		Model string `json:"model"`
	}
	_ = json.Unmarshal([]byte(r.Body), &b)
	return b.Model
}

func seen(t *testing.T, mock string) []rec {
	t.Helper()
	resp, err := http.Get(mock + "/_uat/requests")
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	var out []rec
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		t.Fatal(err)
	}
	return out
}

func reset(t *testing.T) {
	t.Helper()
	for _, m := range []string{mockAURL, mockBURL} {
		resp, err := http.Post(m+"/_uat/reset", "text/plain", nil)
		if err != nil {
			t.Fatal(err)
		}
		resp.Body.Close()
	}
}

// who reports which mock (a, b, or "") served the single request just made, and what it saw.
func who(t *testing.T) (string, rec) {
	t.Helper()
	a, b := seen(t, mockAURL), seen(t, mockBURL)
	switch {
	case len(a) == 1 && len(b) == 0:
		return "a", a[0]
	case len(a) == 0 && len(b) == 1:
		return "b", b[0]
	case len(a)+len(b) == 0:
		return "", rec{}
	}
	t.Fatalf("expected at most one upstream hit, got a=%d b=%d", len(a), len(b))
	return "", rec{}
}

// oracle is the library the plugin itself runs: used to pick users in a given cohort and
// to compare, not to produce the expected routing of the system under test by itself.
type oracle struct{ org *policy.Org }

func (o oracle) decide(user string, groups []string, alias string) gateway.Decision {
	return gateway.Decide(o.org, gateway.RequestInfo{UserID: user, Groups: groups, ModelAlias: alias})
}

func (o oracle) find(t *testing.T, groups []string, alias string, pred func(gateway.Decision) bool) string {
	t.Helper()
	for i := 0; i < 20000; i++ {
		u := fmt.Sprintf("user%d@acme.example", i)
		if pred(o.decide(u, groups, alias)) {
			return u
		}
	}
	t.Fatalf("no user matches the predicate (alias %s, groups %v)", alias, groups)
	return ""
}

func variantOf(exp, variant string) func(gateway.Decision) bool {
	return func(d gateway.Decision) bool { return d.Experiment == exp && d.Variant == variant }
}

func kongLogs(t *testing.T) string {
	t.Helper()
	out, err := exec.Command("docker", "compose", "-p", getenv("UAT_PROJECT", "halos-uat-kong"), "logs", "--no-color", "kong").CombinedOutput() //nolint:gosec // test harness
	if err != nil {
		t.Logf("docker compose logs: %v", err)
	}
	return string(out)
}

func serverPost(t *testing.T, path, reason string) int {
	t.Helper()
	body, _ := json.Marshal(map[string]string{"reason": reason})
	req, _ := http.NewRequest(http.MethodPost, serverURL+path, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		t.Fatal(err)
	}
	defer resp.Body.Close()
	_, _ = io.Copy(io.Discard, resp.Body)
	return resp.StatusCode
}

// until polls f every 2s up to d and returns the elapsed time and whether it became true.
func until(d time.Duration, f func() bool) (time.Duration, bool) {
	t0 := time.Now()
	for time.Since(t0) < d {
		if f() {
			return time.Since(t0), true
		}
		time.Sleep(2 * time.Second)
	}
	return time.Since(t0), false
}

// pct returns the p-th percentile (nearest rank) of ds.
func pct(ds []time.Duration, p int) time.Duration {
	s := slices.Clone(ds)
	slices.Sort(s)
	return s[(len(s)*p+99)/100-1]
}

// ---- scenarios ----

func TestKong(t *testing.T) {
	org, err := policy.Load(os.Getenv("UAT_POLICY"))
	if err != nil {
		t.Fatalf("load UAT_POLICY (run through scripts/uat-kong.sh): %v", err)
	}
	or := oracle{org}
	reset(t)
	var platform = []string{"ai-platform"}
	plain := or.find(t, nil, "sonnet", func(d gateway.Decision) bool { return d.Ring == "ring3-ga" && d.Experiment == "" })
	t.Logf("plain user %s", plain)

	t.Run("routing", func(t *testing.T) {
		const g = "Routing and header hygiene"
		reset(t)
		r := call(t, "/v1/messages", mint(t, plain), msg("sonnet"), nil)
		srv, got := who(t)
		d := or.decide(plain, nil, "sonnet")
		check(t, g, "valid JWT is routed; alias rewritten; ring and release stamped",
			r.code == 200 && srv == "a" && got.model() == "claude-sonnet-4-5" && got.h("x-halo-ring") == d.Ring && got.h("x-halo-release") == d.Release && d.Release != "",
			"%d via mock-%s, upstream model %q, x-halo-ring=%q x-halo-release=%q", r.code, srv, got.model(), got.h("x-halo-ring"), got.h("x-halo-release"))

		reset(t)
		r = call(t, "/v1/messages", mint(t, plain), msg("sonnet"), map[string]string{
			"x-halo-ring": "ring0-harness-team", "x-halo-release": "sha256:evil", "x-halo-experiment": "evil", "x-halo-variant": "evil",
			"X-Halo-Custom": "1", "x-halo-killswitch": "ok", "x-acme-user": "ceo@acme.example"})
		_, got = who(t)
		clean := got.h("x-halo-ring") == d.Ring && got.h("x-halo-release") != "sha256:evil" && got.h("x-halo-experiment") == "" &&
			got.h("x-halo-variant") == "" && got.h("x-halo-custom") == "" && got.h("x-halo-killswitch") == "" && got.h("x-acme-user") == ""
		check(t, g, "spoofed x-halo-* and identity headers are stripped; cohort comes from the verified JWT", r.code == 200 && clean,
			"upstream saw x-halo-ring=%q release=%q experiment=%q variant=%q custom=%q killswitch=%q x-acme-user=%q",
			got.h("x-halo-ring"), got.h("x-halo-release"), got.h("x-halo-experiment"), got.h("x-halo-variant"), got.h("x-halo-custom"), got.h("x-halo-killswitch"), got.h("x-acme-user"))

		reset(t)
		r = call(t, "/v1/messages", mint(t, plain), msg("sonnet"), map[string]string{"x-api-key": "k1", "api-key": "k2", "x-goog-api-key": "k3", "Proxy-Authorization": "Basic k4"})
		_, got = who(t)
		check(t, g, "secure default: no caller credential header reaches the upstream (Authorization, x-api-key, api-key, x-goog-api-key, Proxy-Authorization)",
			r.code == 200 && got.h("Authorization") == "" && got.h("x-api-key") == "" && got.h("api-key") == "" && got.h("x-goog-api-key") == "" && got.h("Proxy-Authorization") == "",
			"upstream saw Authorization=%q x-api-key=%q api-key=%q x-goog-api-key=%q Proxy-Authorization=%q", got.h("Authorization"), got.h("x-api-key"), got.h("api-key"), got.h("x-goog-api-key"), got.h("Proxy-Authorization"))

		reset(t)
		r = call(t, "/v1/messages", mint(t, plain), msg("gpt-4o"), nil)
		a, b := seen(t, mockAURL), seen(t, mockBURL)
		check(t, g, "unknown model is a 400 (fail closed, upstream never hit)",
			r.code == 400 && strings.Contains(r.body, "invalid_request_error") && strings.Contains(r.body, `model \"gpt-4o\" is not permitted by the Halos gateway policy`) && len(a)+len(b) == 0,
			"%s; upstream hits %d", r, len(a)+len(b))

		reset(t)
		r1 := call(t, "/v1/messages/batches", mint(t, plain), `{"requests":[]}`, nil)
		r2 := call(t, "/v1/chat/completions", mint(t, plain), `{"model":"sonnet"}`, nil)
		a, b = seen(t, mockAURL), seen(t, mockBURL)
		check(t, g, "non-model paths never reach an upstream (Kong 404: no route)", r1.code == 404 && r2.code == 404 && len(a)+len(b) == 0,
			"batches %d, chat/completions %d; upstream hits %d", r1.code, r2.code, len(a)+len(b))

		reset(t)
		r = call(t, "/v1/messages/count_tokens", mint(t, plain), msg("sonnet"), nil)
		_, got = who(t)
		check(t, g, "count_tokens is routed and rewritten", r.code == 200 && got.model() == "claude-sonnet-4-5" && strings.Contains(r.body, "input_tokens"),
			"%s; upstream model %q", r, got.model())

		reset(t)
		r = call(t, "/v1/messages", mint(t, plain), strings.Replace(msg("sonnet"), `"max_tokens"`, `"stream":true,"max_tokens"`, 1), nil)
		check(t, g, "SSE passes through (content-type, events)", r.code == 200 && strings.HasPrefix(r.hdr.Get("Content-Type"), "text/event-stream") &&
			strings.Contains(r.body, "event: message_start") && strings.Contains(r.body, "event: message_stop"),
			"%d %s, %d bytes", r.code, r.hdr.Get("Content-Type"), len(r.body))
	})

	t.Run("identity", func(t *testing.T) {
		const g = "Identity"
		forger, err := identitytest.NewIssuer("uat") // same kid as the mock issuer, different key
		if err != nil {
			t.Fatal(err)
		}
		forger.URL = issuer
		forged, _ := forger.Mint(map[string]any{"aud": aud, "email": "alice@acme.example", "groups": platform})
		wrongAud := mintAud(t, "someone-else", "alice@acme.example", platform...)
		for _, tc := range []struct{ name, tok string }{{"missing token", ""}, {"forged JWT (wrong key)", forged}, {"wrong audience", wrongAud}, {"garbage token", "abc.def.ghi"}} {
			reset(t)
			r := call(t, "/v1/messages", tc.tok, msg("sonnet"), map[string]string{"x-acme-user": "alice@acme.example", "x-halo-ring": "ring0-harness-team"})
			a, b := seen(t, mockAURL), seen(t, mockBURL)
			check(t, g, tc.name+" gets 401 by default (JWT identity), upstream never hit",
				r.code == 401 && strings.Contains(r.body, "authentication_error") && r.hdr.Get("WWW-Authenticate") != "" && len(a)+len(b) == 0,
				"%s; WWW-Authenticate %q; upstream hits %d", r, r.hdr.Get("WWW-Authenticate"), len(a)+len(b))
		}
		reset(t)
		r := callHost(t, "anon.kong.test", "/v1/messages", forged, msg("sonnet"), map[string]string{"x-acme-user": "alice@acme.example", "x-halo-ring": "ring0-harness-team"})
		srv, got := who(t)
		check(t, g, "opt-out allow_unverified: an unverified caller is routed anonymously, never into a cohort",
			r.code == 200 && srv == "a" && got.h("x-halo-ring") == "unknown" && got.h("x-halo-experiment") == "",
			"%d via mock-%s, x-halo-ring=%q x-halo-experiment=%q", r.code, srv, got.h("x-halo-ring"), got.h("x-halo-experiment"))

		reset(t)
		tok := mint(t, plain)
		callHost(t, "anon.kong.test", "/v1/messages", tok, msg("sonnet"), nil)
		_, got = who(t)
		check(t, g, "opt-out forward_client_credentials: the caller's Authorization is forwarded (auth-gateway topology)", got.h("Authorization") == "Bearer "+tok,
			"upstream saw Authorization of length %d", len(got.h("Authorization")))
	})

	t.Run("experiments", func(t *testing.T) {
		const g = "Experiments and toggles"
		treated := or.find(t, nil, "opus", variantOf("opus-5-5-canary", "opus-5-5"))
		control := or.find(t, nil, "opus", variantOf("opus-5-5-canary", "control"))
		tok := map[string]string{treated: mint(t, treated), control: mint(t, control)}

		stable := true
		var ev []string
		for _, u := range []string{treated, control} {
			want := map[string]string{treated: "b", control: "a"}[u]
			wantModel := map[string]string{treated: "claude-opus-next", control: "claude-opus-4-1"}[u]
			wantVar := map[string]string{treated: "opus-5-5", control: "control"}[u]
			for i := 0; i < 3; i++ {
				reset(t)
				r := call(t, "/v1/messages", tok[u], msg("opus"), map[string]string{"x-claude-code-session-id": fmt.Sprint("s", i)})
				srv, got := who(t)
				ok := r.code == 200 && srv == want && got.model() == wantModel && got.h("x-halo-experiment") == "opus-5-5-canary" && got.h("x-halo-variant") == wantVar
				stable = stable && ok
				if i == 0 {
					ev = append(ev, fmt.Sprintf("%s -> mock-%s %s (%s)", u, srv, got.model(), got.h("x-halo-variant")))
				}
			}
		}
		check(t, g, "sticky canary: a user stays in the same variant across requests/sessions; treatment is routed to the variant upstream", stable, "%s", strings.Join(ev, "; "))

		match, n := 0, 0
		var split = map[string]int{}
		for i := 0; i < 40; i++ {
			u := fmt.Sprintf("user%d@acme.example", i)
			d := or.decide(u, nil, "opus")
			if d.Experiment == "" {
				continue
			}
			reset(t)
			call(t, "/v1/messages", mint(t, u), msg("opus"), nil)
			_, got := who(t)
			n++
			split[got.h("x-halo-variant")]++
			if got.h("x-halo-variant") == d.Variant && got.h("x-halo-experiment") == d.Experiment {
				match++
			}
		}
		check(t, g, "Kong assigns the same variant as the library for 40 users (same hash everywhere)", n > 0 && match == n && len(split) == 2, "%d/%d match, split %v", match, n, split)

		// A user in the ai-platform group is ring0: the sonnet traffic toggle targets that ring only.
		on := or.find(t, platform, "sonnet", func(d gateway.Decision) bool { return d.Ring == "ring0-harness-team" })
		reset(t)
		r := call(t, "/v1/messages", mint(t, on, platform...), msg("sonnet"), nil)
		srv, got := who(t)
		check(t, g, "traffic toggle on for its cohort (ring0): sonnet routes to the toggle's target", r.code == 200 && srv == "b" && got.model() == "claude-sonnet-5-5",
			"%s -> mock-%s model %q", on, srv, got.model())
		reset(t)
		r = call(t, "/v1/messages", mint(t, plain), msg("sonnet"), nil)
		srv, got = who(t)
		check(t, g, "traffic toggle off for everyone else", r.code == 200 && srv == "a" && got.model() == "claude-sonnet-4-5", "%s -> mock-%s model %q", plain, srv, got.model())

		// Per-alias selection: both canaries cover this user's ring, each only claims its own alias.
		u := or.find(t, nil, "opus", func(d gateway.Decision) bool { return d.Experiment == "opus-5-5-canary" })
		reset(t)
		call(t, "/v1/messages", mint(t, u), msg("opus"), nil)
		_, gotO := who(t)
		reset(t)
		call(t, "/v1/messages", mint(t, u), msg("haiku"), nil)
		_, gotH := who(t)
		reset(t)
		call(t, "/v1/messages", mint(t, u), msg("sonnet"), nil)
		_, gotS := who(t)
		check(t, g, "per-alias experiment selection: each concurrent canary claims only the alias it routes",
			gotO.h("x-halo-experiment") == "opus-5-5-canary" && gotH.h("x-halo-experiment") == "haiku-next-canary" && gotS.h("x-halo-experiment") == "",
			"%s: opus -> %q, haiku -> %q, sonnet -> %q", u, gotO.h("x-halo-experiment"), gotH.h("x-halo-experiment"), gotS.h("x-halo-experiment"))
	})

	t.Run("limits", func(t *testing.T) {
		const g = "Documented halo-kong limits"
		u := mint(t, plain)
		reset(t)
		r := call(t, "/v1/messages", u, msg("multi"), nil)
		srv, got := who(t)
		check(t, g, "multi-target route: only the first target is used", r.code == 200 && srv == "b" && got.model() == "multi-primary", "%d via mock-%s model %q", r.code, srv, got.model())

		reset(t)
		r = call(t, "/v1/messages", u, msg("multi-down"), nil)
		a, b := seen(t, mockAURL), seen(t, mockBURL)
		check(t, g, "no failover: first target unreachable -> Kong 5xx, the second target is never tried", r.code >= 500 && len(a)+len(b) == 0, "%s; upstream hits %d", r, len(a)+len(b))

		reset(t)
		r = call(t, "/v1/messages", u, msg("bedrock-alias"), nil)
		srv, got = who(t)
		check(t, g, "no wire translation: a bedrock target gets the anthropic path/body (only the model is swapped) and no SigV4",
			r.code == 200 && srv == "a" && got.Path == "/v1/messages" && got.model() == "us.anthropic.claude-opus-4-1:0" && got.h("Authorization") == "" && got.h("x-amz-date") == "",
			"%d path %q model %q Authorization %q x-amz-date %q", r.code, got.Path, got.model(), got.h("Authorization"), got.h("x-amz-date"))

		reset(t)
		r = call(t, "/v1beta/models/gemini-default:generateContent", u, `{"contents":[]}`, map[string]string{"x-goog-api-key": u})
		a, b = seen(t, mockAURL), seen(t, mockBURL)
		check(t, g, "gemini wire is not served by halo-kong (no route -> Kong 404, nothing forwarded)", r.code == 404 && len(a)+len(b) == 0, "%s; upstream hits %d", r, len(a)+len(b))
	})

	t.Run("killswitch", func(t *testing.T) {
		const g = "Signed kill switch and configuration"
		treated := or.find(t, nil, "opus", variantOf("opus-5-5-canary", "opus-5-5"))
		tok := mint(t, treated)
		served := func() (string, rec) {
			reset(t)
			call(t, "/v1/messages", tok, msg("opus"), nil)
			return who(t)
		}
		srv, _ := served()
		check(t, g, "before the kill: the treated user is on the canary route", srv == "b", "mock-%s", srv)

		code := serverPost(t, "/api/v1/experiments/opus-5-5-canary/kill", "uat kill drill")
		var got rec
		el, ok := until(killTTL, func() bool {
			var s string
			s, got = served()
			return s == "a"
		})
		check(t, g, "kill via halo-server: halo-kong honours the signed list within its poll interval; user is on control with no experiment attribution",
			code == 200 && ok && got.model() == "claude-opus-4-1" && got.h("x-halo-experiment") == "",
			"kill %d, control after %s (poll is 10s), experiment header %q", code, el.Round(time.Second), got.h("x-halo-experiment"))

		code = serverPost(t, "/api/v1/experiments/opus-5-5-canary/unkill", "")
		el, ok = until(killTTL, func() bool {
			var s string
			s, got = served()
			return s == "b" && got.h("x-halo-experiment") == "opus-5-5-canary"
		})
		check(t, g, "unkill restores the canary route", code == 200 && ok, "unkill %d, restored after %s", code, el.Round(time.Second))

		on := or.find(t, platform, "sonnet", func(d gateway.Decision) bool { return d.Ring == "ring0-harness-team" })
		onTok := mint(t, on, platform...)
		tserved := func() string {
			reset(t)
			call(t, "/v1/messages", onTok, msg("sonnet"), nil)
			s, _ := who(t)
			return s
		}
		tcode := serverPost(t, "/api/v1/toggles/sonnet-next-route/kill", "uat toggle kill")
		el, ok = until(killTTL, func() bool { return tserved() == "a" })
		check(t, g, "a killed toggle stops routing (back to the default route)", tcode == 200 && ok, "toggle kill %d, default route after %s", tcode, el.Round(time.Second))
		serverPost(t, "/api/v1/toggles/sonnet-next-route/unkill", "")
		until(killTTL, func() bool { return tserved() == "b" })

		reset(t)
		r := callHost(t, "bad.kong.test", "/v1/messages", mint(t, plain), msg("sonnet"), nil)
		srv, got = who(t)
		bad := got.h("x-halo-killswitch")
		reset(t)
		call(t, "/v1/messages", mint(t, plain), msg("sonnet"), map[string]string{"x-halo-killswitch": "misconfigured"})
		_, spoofed := who(t)
		logs := kongLogs(t)
		check(t, g, "an unusable kill-switch key keeps traffic flowing but is flagged x-halo-killswitch: misconfigured (and logged at ERROR)",
			r.code == 200 && srv == "a" && bad == "misconfigured" && strings.Contains(logs, "halo-kong: killswitch config invalid"),
			"%d via mock-%s, header %q, error logged %v", r.code, srv, bad, strings.Contains(logs, "halo-kong: killswitch config invalid"))
		check(t, g, "the flag cannot be spoofed on a healthy route", spoofed.h("x-halo-killswitch") == "", "client sent x-halo-killswitch: misconfigured; upstream saw %q", spoofed.h("x-halo-killswitch"))
	})

	// ADR-0006: a Go plugin runs as a separate plugin-server process over a socket. Measure what
	// that hop costs: the same mock upstream through a route with no plugin vs through halo-kong.
	t.Run("latency", func(t *testing.T) {
		const g = "Plugin-server latency (ADR-0006)"
		const n = 60
		tok := mint(t, plain)
		timeIt := func(host, token string) (time.Duration, int) {
			t0 := time.Now()
			r := callHost(t, host, "/v1/messages", token, msg("sonnet"), nil)
			return time.Since(t0), r.code
		}
		for i := 0; i < 5; i++ { // warm both paths (TLS, plugin-server instance)
			timeIt("raw.kong.test", "")
			timeIt("", tok)
		}
		var raw, plug []time.Duration
		ok := true
		for i := 0; i < n; i++ { // interleaved so drift hits both samples alike
			d, c := timeIt("raw.kong.test", "")
			raw, ok = append(raw, d), ok && c == 200
			d, c = timeIt("", tok)
			plug, ok = append(plug, d), ok && c == 200
		}
		reset(t)
		pr, pp := pct(raw, 50), pct(plug, 50)
		over := pp - pr
		// ponytail: loose bound so a busy laptop does not flake; the evidence column is the measurement.
		check(t, g, "halo-kong adds less than 50ms at the median over a no-plugin route to the same upstream",
			ok && over < 50*time.Millisecond,
			"%d sequential requests each (JWT verify + decision + rewrite): no plugin p50 %s p95 %s; halo-kong p50 %s p95 %s; median overhead %s",
			n, pr.Round(10*time.Microsecond), pct(raw, 95).Round(10*time.Microsecond), pp.Round(10*time.Microsecond), pct(plug, 95).Round(10*time.Microsecond), over.Round(10*time.Microsecond))
	})

	t.Run("kong", func(t *testing.T) {
		const g = "Kong health and metrics"
		get := func(path string) (int, string) {
			resp, err := http.Get(statusURL + path)
			if err != nil {
				t.Fatal(err)
			}
			defer resp.Body.Close()
			b, _ := io.ReadAll(resp.Body)
			return resp.StatusCode, string(b)
		}
		sc, sb := get("/status")
		rc, _ := get("/status/ready")
		check(t, g, "Kong /status and /status/ready are healthy", sc == 200 && rc == 200 && strings.Contains(sb, "connections_accepted"), "/status %d, /status/ready %d", sc, rc)
		mc, mb := get("/metrics")
		check(t, g, "prometheus metrics count the traffic, including the plugin's 400 and 401 answers",
			mc == 200 && strings.Contains(mb, "kong_http_requests_total") && strings.Contains(mb, `code="400"`) && strings.Contains(mb, `code="401"`) && strings.Contains(mb, `code="200"`),
			"/metrics %d; has 200/400/401 series", mc)
		logs := kongLogs(t)
		panics := strings.Contains(logs, "panic:") || strings.Contains(logs, "plugin server") && strings.Contains(logs, "exited")
		check(t, g, "the plugin server did not crash or restart during the run", !panics, "no panic/exit lines in Kong's log (%d bytes)", len(logs))
	})
}
