# build context: repo root
FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/halo-kong ./cmd/halo-kong

FROM kong:3.9
COPY --from=build /out/halo-kong /usr/local/bin/halo-kong
