#!/usr/bin/env bash
# Kong OSS UAT: halo-kong as a Go plugin server inside a real, digest-pinned Kong (db-less),
# in front of two mock model upstreams and a halo-server (signed kill list). The decK config is
# generated by `halo gateway deck` from examples/acme-corp + test/uat/kong/policy. The scenarios
# (test/uat/kong, go test -tags uat) write test/uat/KONG-REPORT.md.
#
#   make uat-kong                # build, run, tear down
#   UAT_KEEP=1 make uat-kong     # keep the containers and work dir afterwards
#
# Needs docker (compose v2), go, openssl, git. Kong Enterprise is not covered.
set -euo pipefail
cd "$(dirname "$0")/.."
t0=$SECONDS

# Kong OSS 3.9.x, multi-arch index digest (kong:3.9 at the time of writing). Bump deliberately.
KONG_IMAGE=${UAT_KONG_IMAGE:-kong@sha256:12972ce1ab6396083e56e7d46fce084836c98cc819344bef44a1f583ec3ab191}
export UAT_KONG_IMAGE=$KONG_IMAGE

for tool in docker go openssl; do
  command -v "$tool" >/dev/null || { echo "uat-kong: $tool not found" >&2; exit 1; }
done
docker compose version >/dev/null 2>&1 || { echo "uat-kong: docker compose v2 not found" >&2; exit 1; }

WORK=$(mktemp -d "${TMPDIR:-/tmp}/halos-uat-kong.XXXXXX")
chmod 0755 "$WORK" # mktemp makes it 0700; the Kong image's own user (not ours) must traverse it on Linux engines
export UAT_WORK=$WORK UAT_PROJECT=${UAT_PROJECT:-halos-uat-kong}
export UAT_UID=$(id -u) UAT_GID=$(id -g)
C=(docker compose -f test/uat/kong/docker-compose.yml)

# shellcheck disable=SC2329 # invoked by the EXIT trap
cleanup() {
  rc=$?
  if [ "$rc" != 0 ]; then
    echo "uat-kong: failed (exit $rc); container state and logs:" >&2
    "${C[@]}" ps -a >&2 || true
    "${C[@]}" logs --no-color --tail 80 kong halo-server >&2 || true
  fi
  if [ "${UAT_KEEP:-0}" = 1 ]; then
    echo "uat-kong: keeping project $UAT_PROJECT and $WORK (UAT_KEEP=1); remove with: docker compose -p $UAT_PROJECT down -v"
  else
    "${C[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
    rm -rf "$WORK"
  fi
  echo "uat-kong: total $((SECONDS - t0))s"
}
trap cleanup EXIT

# Refuse to run over a leftover project: ports and state would be shared.
if [ -n "$(docker ps -aq --filter "label=com.docker.compose.project=$UAT_PROJECT")" ]; then
  echo "uat-kong: project $UAT_PROJECT already has containers (docker compose -p $UAT_PROJECT down -v)" >&2
  exit 1
fi

ARCH=$(docker version --format '{{.Server.Arch}}')
mkdir -p "$WORK/bin" "$WORK/keys" "$WORK/data"
chmod 0777 "$WORK/data" # the containers run as the host user, but be explicit for rootless engines
echo "uat-kong: building linux/$ARCH binaries"
build() { CGO_ENABLED=0 GOOS=linux GOARCH=$ARCH go build -trimpath -ldflags "-s -w" "${@:3}" -o "$WORK/bin/$1" "./$2"; }
build halo-kong cmd/halo-kong
build halo-server cmd/halo-server
build uatmock test/uat/mock -tags uat
go build -o "$WORK/halo" ./cmd/halo

# ---- keys, tokens, TLS (the mocks insist on a TLS listener) ----
"$WORK/halo" keys generate --name killswitch --out "$WORK/keys" >/dev/null
openssl rand -hex 24 | tr -d '\n' > "$WORK/keys/gateway.token"
openssl rand -hex 24 | tr -d '\n' > "$WORK/keys/report.token"
openssl req -x509 -newkey rsa:2048 -nodes -days 2 -subj /CN=mock -keyout "$WORK/tls.key" -out "$WORK/tls.crt" 2>/dev/null
chmod 0644 "$WORK/tls.key" "$WORK/keys/"* # readable by the container user; the whole dir is throwaway
UAT_KILL_TOKEN=$(cat "$WORK/keys/gateway.token")
UAT_KILL_PUBKEY=$(cat "$WORK/keys/killswitch.pub")
export UAT_KILL_TOKEN UAT_KILL_PUBKEY

# ---- policy: examples/acme-corp + overlay (two mock upstreams, two concurrent traffic canaries) ----
POL="$WORK/policy"
command cp -R examples/acme-corp "$POL"
rm -f "$POL"/experiments/*.yaml
rm -r "$POL/rollouts" "$POL/evals" # they reference the experiments removed above
command cp -Rf test/uat/kong/policy/. "$POL/"
sed -i.bak 's#https://acme.okta.com/oauth2/default#http://mock-a:8080#' "$POL/halos.yaml"
# Pin each ring to a (fake) release digest so x-halo-release has something to stamp.
n=0
for f in "$POL"/rings/*.yaml; do n=$((n + 1)); printf 'release: sha256:%064d\n' "$n" >> "$f"; done
find "$POL" -name '*.bak' -delete
"$WORK/halo" validate --policy-dir "$POL"
"$WORK/halo" gateway compile --policy-dir "$POL" -o "$WORK/policy.json"

# ---- decK config from the repo's own generator, plus what decK output does not carry ----
"$WORK/halo" gateway deck --policy-dir "$POL" --policy-path /uat/policy.json \
  --killswitch-url http://halo-server:8080/api/v1/gateway/killswitch --killswitch-allow-insecure-in-cluster -o "$WORK/kong.yml"
# UAT additions (not generator output), appended in decK's own layout:
#  - halo-anon-default (Host: anon.kong.test): both secure-default opt-outs (allow_unverified,
#    forward_client_credentials), written the way `halo gateway deck --allow-unverified
#    --forward-client-credentials` would;
#  - halo-bad-killswitch (Host: bad.kong.test): an unusable kill-switch public key (traffic must keep
#    flowing but be flagged x-halo-killswitch: misconfigured);
#  - Kong's prometheus plugin.
cat >> "$WORK/kong.yml" <<'EOF'
    - name: halo-anon-default
      url: http://mock-a:8080
      retries: 0
      plugins:
        - name: halo-kong
          config:
            identity_header: x-acme-user
            allow_unverified: true
            forward_client_credentials: true
            policy_path: /uat/policy.json
      routes:
        - name: anon-messages
          hosts: [anon.kong.test]
          paths: ['~/v1/messages$']
          protocols: [https]
          strip_path: false
          request_buffering: true
    - name: halo-bad-killswitch
      url: http://mock-a:8080
      retries: 0
      plugins:
        - name: halo-kong
          config:
            identity_header: x-acme-user
            killswitch_allow_insecure_in_cluster: true
            killswitch_pubkey: '{vault://env/halo-no-such-pubkey}'
            killswitch_token: '{vault://env/halo-killswitch-token}'
            killswitch_url: http://halo-server:8080/api/v1/gateway/killswitch?cfg=bad
            policy_path: /uat/policy.json
      routes:
        - name: bad-messages
          hosts: [bad.kong.test]
          paths: ['~/v1/messages$']
          protocols: [https]
          strip_path: false
          request_buffering: true
plugins:
  - name: prometheus
    config: {status_code_metrics: true, latency_metrics: true, bandwidth_metrics: true}   # per-request series are off by default
EOF

# ---- up ----
echo "uat-kong: starting Kong ($KONG_IMAGE)"
"${C[@]}" up -d --quiet-pull
wait_http() { # url, want-code-regex, seconds
  for _ in $(seq "$3"); do
    code=$(curl -ks -o /dev/null -w '%{http_code}' "$1" 2>/dev/null || true)
    [[ "$code" =~ $2 ]] && return 0
    sleep 1
  done
  echo "uat-kong: $1 never answered $2 (last: ${code:-none})" >&2
  return 1
}
export UAT_MOCK_A_PORT=${UAT_MOCK_A_PORT:-18081} UAT_MOCK_B_PORT=${UAT_MOCK_B_PORT:-18082} UAT_SERVER_PORT=${UAT_SERVER_PORT:-18090}
export UAT_KONG_PORT=${UAT_KONG_PORT:-18443} UAT_STATUS_PORT=${UAT_STATUS_PORT:-18100}
wait_http "http://127.0.0.1:$UAT_MOCK_A_PORT/.well-known/openid-configuration" '^200$' 60
wait_http "http://127.0.0.1:$UAT_MOCK_B_PORT/_uat/requests" '^200$' 60
wait_http "http://127.0.0.1:$UAT_SERVER_PORT/api/v1/gateway/killswitch" '^(200|401)$' 60
wait_http "http://127.0.0.1:$UAT_STATUS_PORT/status/ready" '^200$' 90

KONG_VERSION=$("${C[@]}" exec -T kong kong version | tr -d '\r')
echo "uat-kong: stack up after $((SECONDS - t0))s ($KONG_VERSION)"

# ---- scenarios ----
export UAT_KONG_VERSION=$KONG_VERSION UAT_KONG_IMAGE UAT_POLICY=$POL UAT_HALO=$WORK/halo UAT_PROJECT UAT_COMPOSE_FILE=test/uat/kong/docker-compose.yml
export UAT_GATEWAY_TOKEN=$UAT_KILL_TOKEN UAT_STARTED=$t0
rc=0
go test -tags uat ./test/uat/kong/ -v -count=1 -timeout 20m "$@" || rc=$?
exit "$rc"
