// Package kong generates the decK declarative config for Kong OSS (db-less)
// that fronts an org's model traffic and attaches the halo-kong plugin.
package kong

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/dshakes/halos/internal/policy"
)

// Options tunes generation. Zero value is usable.
type Options struct {
	PolicyPath     string // snapshot path inside the Kong container
	GroupsHeader   string
	IdentityHeader string // default: org gateway.auth.identityHeader
	ShadowURL      string
	// ShadowToken must be a Kong vault reference (default
	// DefaultShadowTokenRef); plaintext would sit in kong.yml and be readable
	// through the Admin API.
	ShadowToken string
	// AllowHTTP adds plain-http route protocols (local dev only); default https.
	AllowHTTP bool
	// IdentityMode (jwt|trusted_header) and TrustedProxyCIDRs configure halo-kong's
	// caller verification; empty = jwt when org.Identity.Issuer is set.
	IdentityMode      string
	TrustedProxyCIDRs []string
	// KillswitchURL enables halo-kong's kill-switch poller; token and public key
	// are always Kong env-vault references (DefaultKillswitch*Ref). https unless AllowHTTP.
	KillswitchURL string
	// KillswitchAllowInsecure permits a plain-http killswitch URL on a trusted
	// pod network (an in-cluster halo-server Service) and sets the plugin's
	// killswitch_allow_insecure_in_cluster. Default: https required.
	KillswitchAllowInsecure bool
	// RejectUnverified sets the plugin's reject_unverified: model calls without
	// a verified identity get 401 instead of anonymous default routing.
	RejectUnverified bool
	// StripClientCredentials sets the plugin's strip_client_credentials: the
	// caller's Authorization/x-api-key/... never reach the upstream.
	StripClientCredentials bool
}

type config struct {
	FormatVersion string    `yaml:"_format_version"`
	Services      []service `yaml:"services"`
}

type service struct {
	Name           string   `yaml:"name"`
	URL            string   `yaml:"url"`
	Retries        int      `yaml:"retries"`
	ConnectTimeout int      `yaml:"connect_timeout"`
	ReadTimeout    int      `yaml:"read_timeout"`
	WriteTimeout   int      `yaml:"write_timeout"`
	Plugins        []plugin `yaml:"plugins,omitempty"`
	Routes         []route  `yaml:"routes,omitempty"`
}

type route struct {
	Name              string   `yaml:"name"`
	Paths             []string `yaml:"paths"`
	Protocols         []string `yaml:"protocols"`
	StripPath         bool     `yaml:"strip_path"`
	PreserveHost      bool     `yaml:"preserve_host"`
	RequestBuffering  bool     `yaml:"request_buffering"`
	ResponseBuffering bool     `yaml:"response_buffering"`
}

type plugin struct {
	Name   string         `yaml:"name"`
	Config map[string]any `yaml:"config"`
}

// DefaultShadowTokenRef is a Kong env-vault reference: Kong (and halo-kong,
// which resolves it itself) read $HALO_SHADOW_TOKEN.
const DefaultShadowTokenRef = "{vault://env/halo-shadow-token}" //nolint:gosec // vault reference, not a credential

// Kong env-vault references for the kill-switch bearer token and ed25519 public key.
const (
	DefaultKillswitchTokenRef  = "{vault://env/halo-killswitch-token}" //nolint:gosec // vault reference, not a credential
	DefaultKillswitchPubkeyRef = "{vault://env/halo-killswitch-pubkey}"
)

// header is prepended to the generated file: settings decK can't carry.
const header = `# Generated by Halos (internal/gateway/kong). Kong requirements:
#   - nginx_http_client_body_buffer_size = 32m (env KONG_NGINX_HTTP_CLIENT_BODY_BUFFER_SIZE=32m):
#     halo-kong must read the whole body in memory; bodies Kong spools to disk get 413.
#   - Every secret halo-kong reads from its environment (HALO_SHADOW_TOKEN when shadow_url is set;
#     HALO_KILLSWITCH_TOKEN and HALO_KILLSWITCH_PUBKEY when killswitch_url is set) must be in Kong's
#     environment AND in nginx's main-context env list, or the plugin server never sees it (a missing
#     kill-switch key shows up as x-halo-killswitch: misconfigured). nginx_main_env is ONE setting; chain
#     several variables with "; env ", e.g. (verified on Kong OSS 3.9.3):
#       KONG_NGINX_MAIN_ENV="HALO_SHADOW_TOKEN; env HALO_KILLSWITCH_TOKEN; env HALO_KILLSWITCH_PUBKEY"
`

// Exact-match regex routes: only the model calls halo-kong understands reach
// it; everything else under these prefixes (e.g. /v1/messages/batches) gets
// Kong's 404 and never reaches an upstream.
var routes = []struct{ name, path string }{
	{"halo-messages", `~/v1/messages$`},
	{"halo-count-tokens", `~/v1/messages/count_tokens$`},
	{"halo-models", `~/v1/models$`},
	{"halo-bedrock", `~/model/[^/]+/(invoke|invoke-with-response-stream)$`},
	{"halo-responses", `~/v1/responses$`},
}

// Generate renders the decK YAML. One Kong service per upstream (timeouts
// sized for long SSE streams, no retries: a retried LLM call is a duplicated
// bill). Routes hang off the primary service (the upstream most models point
// at) and halo-kong retargets per request, so the other services exist as
// declared, documented targets.
func Generate(org *policy.Org, o Options) ([]byte, error) {
	if org == nil || org.Gateway == nil || len(org.Gateway.Upstreams) == 0 {
		return nil, fmt.Errorf("kong: org has no gateway upstreams")
	}
	g := org.Gateway
	names := make([]string, 0, len(g.Upstreams))
	uses := map[string]int{}
	for n := range g.Upstreams {
		names = append(names, n)
	}
	for _, m := range g.Models {
		uses[m.Primary().Upstream]++
	}
	sort.Strings(names)
	primary := names[0]
	for _, n := range names {
		if uses[n] > uses[primary] {
			primary = n
		}
	}

	id := o.IdentityHeader
	if id == "" {
		id = g.Auth.IdentityHeader
	}
	if id == "" && org.Identity.Issuer == "" {
		return nil, fmt.Errorf("kong: no identity source (set identity.issuer for jwt mode, or gateway.auth.identityHeader / Options.IdentityHeader for trusted_header mode)")
	}
	pc := map[string]any{"policy_path": o.PolicyPath}
	if id != "" {
		pc["identity_header"] = id
	}
	if o.IdentityMode != "" {
		pc["identity_mode"] = o.IdentityMode
	}
	if len(o.TrustedProxyCIDRs) > 0 {
		pc["trusted_proxy_cidrs"] = o.TrustedProxyCIDRs
	}
	if o.GroupsHeader != "" {
		pc["groups_header"] = o.GroupsHeader
	}
	if o.RejectUnverified {
		pc["reject_unverified"] = true
	}
	if o.StripClientCredentials {
		pc["strip_client_credentials"] = true
	}
	if o.ShadowURL != "" {
		tok := o.ShadowToken
		if tok == "" {
			tok = DefaultShadowTokenRef
		}
		if !strings.HasPrefix(tok, "{vault://") {
			return nil, fmt.Errorf("kong: halo-shadow token must be a Kong vault reference like %s, not a literal (it would be stored in kong.yml and exposed by the Admin API)", DefaultShadowTokenRef)
		}
		pc["shadow_url"] = o.ShadowURL
		pc["shadow_token"] = tok
	}
	if o.KillswitchURL != "" {
		httpOK := (o.AllowHTTP || o.KillswitchAllowInsecure) && strings.HasPrefix(o.KillswitchURL, "http://")
		if !strings.HasPrefix(o.KillswitchURL, "https://") && !httpOK {
			return nil, fmt.Errorf("kong: killswitch URL must be https (it carries a bearer token): %q", o.KillswitchURL)
		}
		pc["killswitch_url"] = o.KillswitchURL
		pc["killswitch_token"] = DefaultKillswitchTokenRef
		pc["killswitch_pubkey"] = DefaultKillswitchPubkeyRef
		if o.KillswitchAllowInsecure {
			pc["killswitch_allow_insecure_in_cluster"] = true
		}
	}
	protocols := []string{"https"}
	if o.AllowHTTP {
		protocols = []string{"http", "https"}
	}

	cfg := config{FormatVersion: "3.0"}
	for _, n := range names {
		s := service{Name: "halo-" + n, URL: g.Upstreams[n].URL, ConnectTimeout: 5000, ReadTimeout: 600000, WriteTimeout: 600000}
		if n == primary {
			s.Plugins = []plugin{{Name: "halo-kong", Config: pc}}
			for _, r := range routes {
				s.Routes = append(s.Routes, route{
					Name: r.name, Paths: []string{r.path}, Protocols: protocols,
					RequestBuffering: true, // halo-kong must read the body to rewrite the model
					// ResponseBuffering false: SSE / Bedrock eventstream pass through unbuffered.
				})
			}
		}
		cfg.Services = append(cfg.Services, s)
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, fmt.Errorf("kong: marshal decK config: %w", err)
	}
	return append([]byte(header), out...), nil
}
